filmes = [
    "Crepúsculo dos Deuses",
    "A Malvada",
    "Um Lugar ao Sol",
    "O Maior Espetáculo da Terra",
    "Nasce uma Estrela",
    "Ladrão de Casaca",
    "A Volta ao Mundo em 80 Dias",
    "A Ponte do Rio Kwai",
    "Um Corpo que Cai",
    "Ben-Hur",
    "Psicose",
    "Amor, Sublime Amor",
    "Lawrence da Arábia",
    "O Sol É para Todos",
    "Música no Coração",
    "Doutor Jivago",
    "O Bom, o Mau e o Feio",
    "A Primeira Noite de um Homem",
    "2001: Uma Odisseia no Espaço",
    "Butch Cassidy",
    "Patton - Rebelde ou Herói?",
    "Operação França",
    "O Poderoso Chefão",
    "O Exorcista",
    "O Poderoso Chefão - Parte II",
    "Um Estranho no Ninho",
    "Rocky, um Lutador",
    "Star Wars: Episódio IV - Uma Nova Esperança",
    "O Franco Atirador",
    "Kramer vs. Kramer",
    "Touro Indomável",
    "Carruagens de Fogo",
    "E.T. - O Extraterrestre",
    "Star Wars: Episódio VI - O Retorno do Jedi",
    "O Exterminador do Futuro",
    "De Volta para o Futuro",
    "Platoon",
    "Os Intocáveis",
    "Rain Man",
    "Nascido em 4 de Julho",
    "Dança com Lobos",
    "O Silêncio dos Inocentes",
    "Os Imperdoáveis",
    "A Lista de Schindler",
    "Forrest Gump",
    "Coração Valente",
    "O Paciente Inglês",
    "Titanic",
    "Shakespeare Apaixonado",
    "Beleza Americana",
    "Gladiador",
    "Uma Mente Brilhante",
    "Chicago",
    "O Senhor dos Anéis: O Retorno do Rei",
    "Menina de Ouro",
    "Crash - No Limite",
    "Os Infiltrados",
    "Onde os Fracos Não Têm Vez",
    "Quem Quer Ser um Milionário?",
    "Guerra ao Terror",
    "O Discurso do Rei"
]

ano = int(input("Digite o ano em que você nasceu: "))

if 1950 <= ano <= 2010:
    print(f"O filme do seu ano de nascimento é: {filmes[ano - 1950]}")
else:
    print("O ano precisa estar entre 1950 e 2010.")
